name: promodoro
description: "A new Flutter project."

publish_to: "none"

version: 1.1.1+4

environment:
  sdk: ^3.9.0

dependencies:
  audioplayers: ^6.0.0
  cupertino_icons: ^1.0.8
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.14.4
  flutter_local_notifications: ^17.0.0
  flutter_native_splash: ^2.4.7
  get: ^4.7.3
  shared_preferences: ^2.5.4
  timezone: ^0.9.2

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/

flutter_native_splash:
  color: "#000000"

  branding: assets/logo.png
  branding_mode: contain

  android_12:
    color: "#000000"

  fullscreen: true

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/app_icon.png"

  adaptive_icon_background: "#000000"
  adaptive_icon_foreground: "assets/app_icon.png"
